/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheoryRouteImport } from './routes/theory'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as BeatRecipesRouteImport } from './routes/beat-recipes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AiProducerRouteImport } from './routes/ai-producer'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedLearnLevelRouteImport } from './routes/_authenticated/learn.$level'
import { Route as AuthenticatedLearnLevelLessonRouteImport } from './routes/_authenticated/learn.$level.$lesson'

const TheoryRoute = TheoryRouteImport.update({
  id: '/theory',
  path: '/theory',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const BeatRecipesRoute = BeatRecipesRouteImport.update({
  id: '/beat-recipes',
  path: '/beat-recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AiProducerRoute = AiProducerRouteImport.update({
  id: '/ai-producer',
  path: '/ai-producer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnLevelRoute = AuthenticatedLearnLevelRouteImport.update({
  id: '/learn/$level',
  path: '/learn/$level',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnLevelLessonRoute =
  AuthenticatedLearnLevelLessonRouteImport.update({
    id: '/$lesson',
    path: '/$lesson',
    getParentRoute: () => AuthenticatedLearnLevelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-producer': typeof AiProducerRoute
  '/auth': typeof AuthRoute
  '/beat-recipes': typeof BeatRecipesRoute
  '/plugins': typeof PluginsRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/theory': typeof TheoryRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/learn/': typeof LearnIndexRoute
  '/learn/$level': typeof AuthenticatedLearnLevelRouteWithChildren
  '/learn/$level/$lesson': typeof AuthenticatedLearnLevelLessonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-producer': typeof AiProducerRoute
  '/auth': typeof AuthRoute
  '/beat-recipes': typeof BeatRecipesRoute
  '/plugins': typeof PluginsRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/theory': typeof TheoryRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/learn': typeof LearnIndexRoute
  '/learn/$level': typeof AuthenticatedLearnLevelRouteWithChildren
  '/learn/$level/$lesson': typeof AuthenticatedLearnLevelLessonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai-producer': typeof AiProducerRoute
  '/auth': typeof AuthRoute
  '/beat-recipes': typeof BeatRecipesRoute
  '/plugins': typeof PluginsRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/theory': typeof TheoryRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/learn/': typeof LearnIndexRoute
  '/_authenticated/learn/$level': typeof AuthenticatedLearnLevelRouteWithChildren
  '/_authenticated/learn/$level/$lesson': typeof AuthenticatedLearnLevelLessonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-producer'
    | '/auth'
    | '/beat-recipes'
    | '/plugins'
    | '/practice'
    | '/profile'
    | '/settings'
    | '/theory'
    | '/progress'
    | '/learn/'
    | '/learn/$level'
    | '/learn/$level/$lesson'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-producer'
    | '/auth'
    | '/beat-recipes'
    | '/plugins'
    | '/practice'
    | '/profile'
    | '/settings'
    | '/theory'
    | '/progress'
    | '/learn'
    | '/learn/$level'
    | '/learn/$level/$lesson'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ai-producer'
    | '/auth'
    | '/beat-recipes'
    | '/plugins'
    | '/practice'
    | '/profile'
    | '/settings'
    | '/theory'
    | '/_authenticated/progress'
    | '/learn/'
    | '/_authenticated/learn/$level'
    | '/_authenticated/learn/$level/$lesson'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiProducerRoute: typeof AiProducerRoute
  AuthRoute: typeof AuthRoute
  BeatRecipesRoute: typeof BeatRecipesRoute
  PluginsRoute: typeof PluginsRoute
  PracticeRoute: typeof PracticeRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  TheoryRoute: typeof TheoryRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theory': {
      id: '/theory'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof TheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beat-recipes': {
      id: '/beat-recipes'
      path: '/beat-recipes'
      fullPath: '/beat-recipes'
      preLoaderRoute: typeof BeatRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-producer': {
      id: '/ai-producer'
      path: '/ai-producer'
      fullPath: '/ai-producer'
      preLoaderRoute: typeof AiProducerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$level': {
      id: '/_authenticated/learn/$level'
      path: '/learn/$level'
      fullPath: '/learn/$level'
      preLoaderRoute: typeof AuthenticatedLearnLevelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$level/$lesson': {
      id: '/_authenticated/learn/$level/$lesson'
      path: '/$lesson'
      fullPath: '/learn/$level/$lesson'
      preLoaderRoute: typeof AuthenticatedLearnLevelLessonRouteImport
      parentRoute: typeof AuthenticatedLearnLevelRoute
    }
  }
}

interface AuthenticatedLearnLevelRouteChildren {
  AuthenticatedLearnLevelLessonRoute: typeof AuthenticatedLearnLevelLessonRoute
}

const AuthenticatedLearnLevelRouteChildren: AuthenticatedLearnLevelRouteChildren =
  {
    AuthenticatedLearnLevelLessonRoute: AuthenticatedLearnLevelLessonRoute,
  }

const AuthenticatedLearnLevelRouteWithChildren =
  AuthenticatedLearnLevelRoute._addFileChildren(
    AuthenticatedLearnLevelRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedLearnLevelRoute: typeof AuthenticatedLearnLevelRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedLearnLevelRoute: AuthenticatedLearnLevelRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiProducerRoute: AiProducerRoute,
  AuthRoute: AuthRoute,
  BeatRecipesRoute: BeatRecipesRoute,
  PluginsRoute: PluginsRoute,
  PracticeRoute: PracticeRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  TheoryRoute: TheoryRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
